- type: jobRequirementOverride
  id: Reduced
  jobs:
    Captain:
    - !type:RoleTimeRequirement
      role: HeadOfSecurity
      time: 1h
    - !type:RoleTimeRequirement
      role: Quartermaster
      time: 1h
    - !type:RoleTimeRequirement
      role: ChiefEngineer
      time: 1h
    - !type:RoleTimeRequirement
      role: ChiefMedicalOfficer
      time: 1h
    - !type:RoleTimeRequirement
      role: ResearchDirector
      time: 1h
    HeadOfPersonnel:
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 5h
    HeadOfSecurity:
    - !type:RoleTimeRequirement
      role: Warden
      time: 1h
    - !type:RoleTimeRequirement
      role: Detective
      time: 1h
    - !type:RoleTimeRequirement
      role: SecurityOfficer
      time: 1h
    - !type:DepartmentTimeRequirement
      department: Security
      time: 5h
    Warden:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 3h
    Detective:
    - !type:RoleTimeRequirement
      role: SecurityOfficer
      time: 1h
    SecurityOfficer:
    - !type:RoleTimeRequirement
      role: SecurityCadet
      time: 1h
    SecurityCadet:
    - !type:OverallPlaytimeRequirement
      time: 2h
    Quartermaster:
    - !type:RoleTimeRequirement
      role: CargoTechnician
      time: 1h
    - !type:RoleTimeRequirement
      role: SalvageSpecialist
      time: 1h
    ChiefEngineer:
    - !type:RoleTimeRequirement
      role: AtmosphericTechnician
      time: 1h
    - !type:RoleTimeRequirement
      role: StationEngineer
      time: 1h
    AtmosphericTechnician:
    - !type:RoleTimeRequirement
      role: StationEngineer
      time: 1h
    StationEngineer:
    - !type:RoleTimeRequirement
      role: TechnicalAssistant
      time: 1h
    ChiefMedicalOfficer:
    - !type:RoleTimeRequirement
      role: Chemist
      time: 2h
    - !type:RoleTimeRequirement
      role: MedicalDoctor
      time: 2h
    Chemist:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 2h
    MedicalDoctor:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 3h
    - !type:RoleTimeRequirement
      role: MedicalIntern
      time: 1h
    ResearchDirector:
    - !type:RoleTimeRequirement
      role: Scientist
      time: 2h
    Scientist:
    - !type:RoleTimeRequirement
      role: ResearchAssistant
      time: 1h